# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
before_all do
  update_fastlane
end

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight on CI"
  lane :beta_ci do
    setup_ci

    sync_code_signing(
      type: "appstore",
      readonly: is_ci
    )

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    api_key = app_store_connect_api_key(
            key_id: "DSZ32H33CL",
            issuer_id: "fb8accf3-4375-49f8-9bd0-449e0ef34160",
            key_filepath: "./ci.p8",
    #         duration: 1200, # optional (maximum 1200)
    #         in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)
  end

  desc "Push a new beta build to TestFlight on CI"
  lane :beta_local do
    sync_code_signing(
        type: "appstore",
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    api_key = app_store_connect_api_key(
        key_id: "2YVM98BL32",
        issuer_id: "fb8accf3-4375-49f8-9bd0-449e0ef34160",
        key_filepath: "./local.p8",
#         duration: 1200, # optional (maximum 1200)
#         in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(api_key: api_key)
  end

  lane :release_local do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end
