# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
before_all do
  update_fastlane
end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new beta version to the Google Play"
  lane :beta do
    upload_to_play_store(track: "beta", aab: "../build/app/outputs/bundle/release/app-release.aab")
  end

  # TODO https://docs.fastlane.tools/actions/upload_to_play_store/
  desc "Deploy a production version to Google Play"
  lane :release do
    upload_to_play_store(track: "production", aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
end
