name: prerelease_ios

on:
  release:
    types:
      - prereleased

jobs:
  deploy_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Bundle install
        run: cd ./ios && bundle install

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install

      - name: Flutter build release
        run: |
          flutter build ios --release --no-codesign --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}

      - name: Dump Secrets
        run: |
          cd ios/
          echo "${{secrets.CONNECT_KEY}}" > ci.p8

      - name: Deploy to TestFlight
        run: |
          cd ./ios && bundle exec fastlane beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT: ${{ secrets.MATCH_GIT }}
          CONNECT_KEY_ID: ${{ secrets.CONNECT_KEY_ID }}
          CONNECT_ISSUER_ID: ${{ secrets.CONNECT_ISSUER_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}